import { Container } from '@/components/Container'
import QueryProvider from '@/components/QueryProvider/QueryProvider'
import { Header } from '@/Ui/Header/Header'
import type { Metadata } from 'next'
import { Fira_Code, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
	variable: '--font-sans',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '900'],
	display: 'swap',
})

const firaCode = Fira_Code({
	variable: '--font-mono',
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.variable} ${firaCode.variable} antialiased`}>
				<QueryProvider>
					<Header />
					<Container>{children}</Container>
					<div id='portal-root' />
				</QueryProvider>
			</body>
		</html>
	)
}
